### PR TITLE
Generate config/effector descriptions for yaml-only blueprints

### PR DESCRIPTION
**Pull request by iyovcheva**

### CODE REVIEW

**Comment by tbouron** [comment]
Doing a `/path/to/brooklyn list-objects --yaml <path-to-yaml/bom>` works, I can see my `catalog.bom` YAML blueprint listed into the generated `items.(js|json)` with my configuration keys. However I was expected to see only my YAML. Currently, all entities and catalog items are listed along my YAML blueprint.

I reckon that's logical as by default, the command grab all the jars within the classpath. I tried to specified `--jar` with nothing behind but it's not accepted. I would allow that for the command to become: `brooklyn/list-objects --yaml <path/to/bom> --jars`

WDYT?

**Comment by iyovcheva** [comment]
retest this please

**Comment by tbouron** [comment]
Just did, the output is the same, it contains all entities

**Comment by iyovcheva** [comment]
@tbouron this message makes Jenkins to run tests again :)

**Comment by ahgittin** [comment]
This looks good.  Making a few changes:

* the `type` of a yaml item should be its id not its underlying java type
* `itemDescriptor` generation for yaml items moved to `ItemDescriptors`
* support `yaml` as a list, like `jars`; and allow a user to supply both; and if just yaml is supplies, it does not scan classes; if neither supplied, as before, it looks at `INITIAL_CLASSPATH`
* share more code between yaml and java block
* use `filename.toLowerCase().endsWith(".yaml")` rather than case-sensitive `contains`
* it just builds one catalog, even with multiple items; if user wants multiple catalogs, they should just run this multiple times
* use our `Strings` class to test for null/empty

then i'll merge

**Pull request merged**
