### PR TITLE
Remove deprecated REST API endpoints

### PR DESCRIPTION
**Pull request by tbouron**
This removes the deprecated REST API endpoints from Brooklyn 0.7.0. It also fixes the launcher configuration (as the `VersionApi` has been entirely removed) and unit tests.

Please note that I didn't touch the `LocationApi` for a very specific reason: currently, this is the only of getting the locations defined within `brooklyn.properties`/`brooklyn.cfg` files. We need to figure out first how to handle those locations before removing the endpoints. As you can see, this is not in the scope of this PR.

### CODE REVIEW

**Comment by tbouron** [comment]
BTW, I also checked the JSGUI and it does not use any of the deprecated call so you are good on this part

**Comment by geomacy** [comment]
👍  lgtm; have also tested a variety of `br` command line operations against this without problems. Will merge.

**Comment by tbouron** [comment]
Awesome, thanks @geomacy! Could you also take a look at https://github.com/apache/brooklyn-client/issues/45 please? That will avoid the build to fail

**Comment by geomacy** [comment]
@tbouron that's done thanks

**Pull request merged**
