### PR TITLE
Bump karaf to 4.2.1 to allow running under JDK 11

### PR DESCRIPTION
**Pull request by kemitix**
This upgrades the `karaf` container to the 4.2.1 release. This version of `karaf` supports running under Java 11.

Additional dependencies have been added to support `brooklyn-server` running under Java 11.

An unused import on a Corba package has been removed.

This PR works in tandem with apache/brooklyn-ui#74.

### CODE REVIEW

**Comment by aledsage** [comment]
Eye-balling the changes, they look good. A few things to raise:
1. Would be good to upgrade our jetty.version to 9.4.x (from 9.3.24) to match karaf's version. But @kemitix has tested with us including both bundle versions in karaf and it's working. So we can do that separately.
2. A little uncomfortable about having two `pax-web` versions - what needs 6.0.6 explicitly? What version is in karaf 4.2.1?
3. The karaf.plugin.version in 4.1.5 onwards does not respect maven's `-s /path/to/settings.xml` (as described in http://karaf.922171.n3.nabble.com/4-1-5-and-Karaf-Maven-Plugin-td4052587.html - I've been meaning to create a formal bug report for that!). This shouldn't affect Brooklyn because Apache Jenkins uses the standard location `~/.m2/settings.xml`, but might impact downstream projects.

I'd like to have some time to build this locally and do some more testing before we merge it please.

**Comment by kemitix** [comment]
@aledsage I've upgraded jetty to match karaf 4.2.1. I've also upgraded pax-web to the same version as karaf 4.2.1, so there is only the one version being deployed.

**Comment by kemitix** [comment]
please retest this

**Comment by kemitix** [comment]
retest this please

**Comment by kemitix** [comment]
I have raised an issue on Karaf for the karaf-maven-plugin issue: https://issues.apache.org/jira/browse/KARAF-5932

I have a fix which I will submit as a PR against karaf.

**Comment by kemitix** [comment]
Pull request for KARAF-5932: apache/karaf#614

**Comment by aledsage** [comment]
The PR build's test failures look related to the change, e.g.:
```
2018-09-28 10:56:56,059 INFO  - TESTNG FAILED CONFIGURATION: "Surefire test" - @BeforeClass org.apache.brooklyn.rest.testing.BrooklynRestApiTest.setUpClass() finished in 0 ms
java.lang.NoClassDefFoundError: org/eclipse/jetty/server/SessionManager
	at org.apache.cxf.transport.http_jetty.JettyHTTPServerEngineFactory.getOrCreate(JettyHTTPServerEngineFactory.java:117)
	at org.apache.cxf.transport.http_jetty.JettyHTTPServerEngineFactory.createJettyHTTPServerEngine(JettyHTTPServerEngineFactory.java:273)
	at org.apache.cxf.transport.http_jetty.JettyHTTPDestination.retrieveEngine(JettyHTTPDestination.java:122)
	at org.apache.cxf.transport.http_jetty.JettyHTTPDestination.finalizeConfig(JettyHTTPDestination.java:154)
	at org.apache.cxf.transport.http.HTTPTransportFactory.getDestination(HTTPTransportFactory.java:281)
	at org.apache.cxf.endpoint.ServerImpl.initDestination(ServerImpl.java:84)
	at org.apache.cxf.endpoint.ServerImpl.<init>(ServerImpl.java:63)
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:173)
	at org.apache.brooklyn.rest.testing.BrooklynRestResourceTest.startServer(BrooklynRestResourceTest.java:100)
	at org.apache.brooklyn.rest.testing.BrooklynRestResourceTest.initClass(BrooklynRestResourceTest.java:80)
	at org.apache.brooklyn.rest.testing.BrooklynRestApiTest.setUpClass(BrooklynRestApiTest.java:66)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.SessionManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more
```

**Comment by kemitix** [comment]
SessionManager went away in jetty 9.4.x. I caught that in production code
but obviously missed it in the test code. I'll have a look at it.

**Comment by geomacy** [comment]
Ha! Wish I'd looked at Aled's [comment](https://github.com/apache/brooklyn-server/pull/1002#issuecomment-425631956) today before I started trying to test it, then I might have avoided some struggle before reporting I get

```
java.lang.NoClassDefFoundError: org/eclipse/jetty/server/SessionManager
	at org.apache.cxf.transport.http_jetty.JettyHTTPServerEngineFactory.getOrCreate(JettyHTTPServerEngineFactory.java:117)
	at org.apache.cxf.transport.http_jetty.JettyHTTPServerEngineFactory.createJettyHTTPServerEngine(JettyHTTPServerEngineFactory.java:273)
	at org.apache.cxf.transport.http_jetty.JettyHTTPDestination.retrieveEngine(JettyHTTPDestination.java:122)
	at org.apache.cxf.transport.http_jetty.JettyHTTPDestination.finalizeConfig(JettyHTTPDestination.java:154)
	at org.apache.cxf.transport.http.HTTPTransportFactory.getDestination(HTTPTransportFactory.java:281)
	at org.apache.cxf.endpoint.ServerImpl.initDestination(ServerImpl.java:84)
	at org.apache.cxf.endpoint.ServerImpl.<init>(ServerImpl.java:63)
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:173)
	at org.apache.brooklyn.rest.testing.BrooklynRestResourceTest.startServer(BrooklynRestResourceTest.java:100)
	at org.apache.brooklyn.rest.testing.BrooklynRestResourceTest.initClass(BrooklynRestResourceTest.java:80)
	at org.apache.brooklyn.rest.resources.BundleAndTypeResourcesTest.initClass(BundleAndTypeResourcesTest.java:110)
	at org.apache.brooklyn.rest.testing.BrooklynRestApiTest.setUpClass(BrooklynRestApiTest.java:66)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.SessionManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
```
😣

**Comment by geomacy** [comment]
Also worth noting what I saw last week - if you sync this and brooklyn-ui#74, then try to build from the parent `brooklyn`, it breaks at once with 
```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.ops4j.pax.web:pax-web-spi:jar is missing. @ org.apache.brooklyn.ui.modularity:brooklyn-ui-module-api:[unknown-version], /Users/geoff/workspaces/github.com/apache/brooklyn/brooklyn-ui/modularity-server/module-api/pom.xml, line 72, column 21
[ERROR] 'dependencies.dependency.version' for org.ops4j.pax.web:pax-web-extender-whiteboard:jar must be a valid version but is '${pax-web.version}'. @ org.apache.brooklyn.ui.modularity:brooklyn-ui-module-registry:[unknown-version], /Users/geoff/workspaces/github.com/apache/brooklyn/brooklyn-ui/modularity-server/module-registry/pom.xml, line 64, column 22
[ERROR] 'dependencies.dependency.version' for org.ops4j.pax.web:pax-web-extender-whiteboard:jar must be a valid version but is '${pax-web.version}'. @ org.apache.brooklyn.ui.modularity:brooklyn-ui-proxy:[unknown-version], /Users/geoff/workspaces/github.com/apache/brooklyn/brooklyn-ui/modularity-server/proxy/pom.xml, line 49, column 22
 @ 
```

**Comment by kemitix** [comment]
@geomacy Just pushed a couple of commits to the brooklyn-ui PR that should fix the missing `pax-web.version`.

I'll be digging into fixing the SessionManager problem tomorrow.

**Comment by kemitix** [comment]
Current status: Brooklyn is failing to load the `brooklyn-rest-resources` feature with a `NoClassDefFoundError` for `javax.xml.ws.WebServiceFeature`, despite efforts to add it as a dependency.

**Comment by kemitix** [comment]
There are problems with getting the Brooklyn UI to work with the `jetty` and `cxf` upgrades. The OSGI feature `brooklyn-rest-resources` fails to start, reporting a `NoClassDefFoundError` for `javax.xml.ws.*`. The suggestion from the [Karaf Mailing List](http://karaf.922171.n3.nabble.com/Karaf-4-2-1-JDK-10-provide-jax-ws-td4054044.html), is to add the OSGI wrapper for the JAXWS API: `mvn:org.apache.servicemix.specs/org.apache.servicemix.specs.jaxws-api-2.2/2.9.0` bundle. However, I haven't been able to make this work.

The task of upgrading `jetty` and `cxf` will be deferred for now: https://issues.apache.org/jira/browse/BROOKLYN-604

**Pull request merged**
