### PR TITLE
Move chef from brooklyn-software-base to own module in brooklyn-library

### PR DESCRIPTION
**Pull request by aledsage**
See https://github.com/apache/brooklyn-library/pull/129 for where this code is being moved to.

### CODE REVIEW

**Comment by tbouron** [comment]
@aledsage Just tested this with https://github.com/apache/brooklyn-library/pull/129, works great but requires to be rebased on the latest master.

After that, good to merge 👍

**Comment by aledsage** [comment]
Jenkins failed for reasons related to build environment, rather than this PR:
```
GitHub pull request #826 of commit d113c7f856c1c3a9855d1fb71c5188234fba3561, no merge conflicts.
Setting status of d113c7f856c1c3a9855d1fb71c5188234fba3561 to PENDING with url https://builds.apache.org/job/brooklyn-server-pull-requests/2627/ and message: 'Build started sha1 is merged.'
Using context: Jenkins: brooklyn-server-pull-request
[EnvInject] - Loading node environment variables.
ERROR: SEVERE ERROR occurs
org.jenkinsci.lib.envinject.EnvInjectException: hudson.remoting.ChannelClosedException: channel is already closed
	at org.jenkinsci.plugins.envinject.service.EnvironmentVariablesNodeLoader.gatherEnvVarsForNode(EnvironmentVariablesNodeLoader.java:95)
	at org.jenkinsci.plugins.envinject.EnvInjectListener.loadEnvironmentVariablesNode(EnvInjectListener.java:80)
	at org.jenkinsci.plugins.envinject.EnvInjectListener.setUpEnvironment(EnvInjectListener.java:43)
	at hudson.model.AbstractBuild$AbstractBuildExecution.createLauncher(AbstractBuild.java:528)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:448)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:542)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
Caused by: hudson.remoting.ChannelClosedException: channel is already closed
	at hudson.remoting.Channel.send(Channel.java:605)
	at hudson.remoting.Request.call(Request.java:130)
	at hudson.remoting.Channel.call(Channel.java:829)
	at hudson.FilePath.act(FilePath.java:1081)
	at org.jenkinsci.plugins.envinject.service.EnvironmentVariablesNodeLoader.gatherEnvVarsForNode(EnvironmentVariablesNodeLoader.java:64)
	... 8 more
Caused by: java.io.IOException
	at hudson.remoting.Channel.close(Channel.java:1292)
	at hudson.slaves.ChannelPinger$1.onDead(ChannelPinger.java:180)
	at hudson.remoting.PingThread.ping(PingThread.java:130)
	at hudson.remoting.PingThread.run(PingThread.java:86)
Caused by: java.util.concurrent.TimeoutException: Ping started at 1506533277118 hasn't completed by 1506533517119
	... 2 more
[EnvInject] - [ERROR] - SEVERE ERROR occurs: channel is already closed
```

**Comment by aledsage** [comment]
retest this please

**Comment by tbouron** [comment]
Looks like something is wrong on Jenkins @aledsage 
```
org.apache.brooklyn.camp.brooklyn.VanillaSoftwareProcessYamlTest.testAlternativeServiceUpPolling()
Build timed out (after 60 minutes). Marking the build as aborted.
```

**Comment by drigodwin** [comment]
retest this please

**Pull request merged**
