### PR TITLE
Tweaks on 866

### PR DESCRIPTION
**Pull request by ahgittin**
Builds on #866 - closes it and adds a few tweaks.

### CODE REVIEW

**Comment by aledsage** [comment]
retest this please

Test failure is unrelated, and thus requires attention separately from this PR:
```
java.lang.AssertionError: expected [2] but found [1]
	at org.apache.brooklyn.test.framework.TestEffectorTest.testEffectorFailureRetriedUpToMaxAttempts(TestEffectorTest.java:247)
```

**Comment by ahgittin** [comment]
retest this please

non-deterministic test failure this time is

```
Error Message

expected one element but was: <{myKey=myDefault}, {myKey=valIsV1}>
Stacktrace

java.lang.IllegalArgumentException: expected one element but was: <{myKey=myDefault}, {myKey=valIsV1}>
	at org.apache.brooklyn.enricher.stock.UpdatingMapTest.testUpdateMapEmitsEventOnChange(UpdatingMapTest.java:126)
```

also note the one in previous comment.  the list seems to be growing again :(

**Comment by ahgittin** [comment]
ran this locally, got a real failure @aledsage:

```
Failed tests: 
  BrooklynLauncherUpgradeCatalogOsgiTest.testRemoveLegacyItems:92->AbstractBrooklynLauncherRebindTest.assertCatalogConsistsOfIds:183->AbstractBrooklynLauncherRebindTest.assertTypeRegistryConsistsOfIds:206 Expected [two:1.0.0, three:0.2.0, four:0.1.0], found [two:1.0.0, two:0.1.0, four:0.1.0, one:0.1.0, three:0.2.0, three:0.1.0] expected [true] but found [false]
```

**Comment by aledsage** [comment]
@ahgittin I'm guessing your comment about the failing `BrooklynLauncherUpgradeCatalogOsgiTest.testRemoveLegacyItems` was meant against https://github.com/apache/brooklyn-server/pull/867, instead of this PR? I've fixed it in #867 and jenkins is running again.

Assuming that is the case, then do you want to merge this PR after #867 (given it may well cause merge conflicts, which will be faster to handle here?)

**Pull request merged**
