### PR TITLE
Updates karaf to 4.1.2

### PR DESCRIPTION
**Pull request by m4rkmckenna**
* Jetty update to 9.3.14.v20161028

### CODE REVIEW

**Comment by neykov** [comment]
:+1: glad to see so few changes needed.

**Comment by m4rkmckenna** [comment]
@neykov Biggest change is the logging which im working through in https://github.com/apache/brooklyn-dist/issues/101

**Comment by geomacy** [comment]
LGTM apart from Pax exam failures.

**Comment by m4rkmckenna** [comment]
@geomacy PAX exam tests fixed with latest commit in https://github.com/apache/brooklyn-dist/pull/101

**Pull request merged**
