### PR TITLE
[BROOKLYN-584] Add support for recent jclouds's ContextLinking

### PR DESCRIPTION
**Pull request by andreaturli**
- add support for user-defined Guice modules
- add support for ContextLinking

### CODE REVIEW

**Comment by duncangrant** [comment]
@andreaturli Might be worth adding a docs change to https://brooklyn.apache.org/v/latest/locations/index.html#openstack?

**Comment by andreaturli** [comment]
thanks @duncangrant and @geomacy 

Do you guys think the docs should be part of the same PR?

**Comment by duncangrant** [comment]
@andreaturli No - shouldn't be part of this PR.  I just wrote the comment as a reminder.

**Comment by geomacy** [comment]
@andreaturli @duncangrant  I agree it shouldn't be part of this PR, just think it's worth documenting

**Pull request merged**
