### PR TITLE
Allow equivalent plans when replacing

### PR DESCRIPTION
**Pull request by ahgittin**
Needed because our routines sometimes rewrite the plan

### CODE REVIEW

**Comment by ahgittin** [comment]
Follow-up to #746 making it slightly more forgiving when replacing, should fix issues when dealing with complex catalogs/blueprints

**Comment by geomacy** [comment]
test failure is real, in `CatalogResourceTest`

**Comment by geomacy** [comment]
For `testOsgiBundleWithBom` it's just an update needed to the test expectation - there are now more tags than before on the result:
```
    "equivalent-plan(A8FA402166F072F19CFE88AEA200B001)",
    "equivalent-plan(A74550A5F94D4AD144AC5EB816DE6C45)",
    {
      "traits": [
        ...
      ]
    }
```

**Comment by ahgittin** [comment]
thanks @geomacy - fixed and merged

**Pull request merged**
