### PR TITLE
[OSGi] Graceful shutdown

### PR DESCRIPTION
**Pull request by neykov**
Implement shutdown handler, call shutdown hooks at the appropriate time.

Depends on (but not based on):
  * #55
  * #65
  * #66

### CODE REVIEW

**Comment by ahgittin** [comment]
config conflicts with some of the others, i think easily fixed in https://github.com/ahgittin/brooklyn-server/commit/b6b5fb62cec79a919dd00f4042d857337104ad75, but worth an eyeball that it is now all correct

**Comment by ahgittin** [comment]
code looks nice and elegant.  the jenkins compile failure is suspicious.  building on my machine now.

personally don't like the name "container framework" -- that sounds like clocker to me -- but i'm guessing it's an osgi thing.  references to it could say "osgi container framework" or something less ambiguous (but very minor.)

**Comment by ahgittin** [comment]
builds fine for me so i think it's just a case that this has dependencies which aren't included in the PR

@neykov curious why you didn't build on the dependent PRs here?

**Comment by neykov** [comment]
Jenkins build failure due to the branch being based on master instead of previous PRs. Gave up piling one on the other :) - that's why there are minor merge conflicts here and there.

As for naming, agree that terms could be more descriptive.

**Comment by neykov** [comment]
Not basing on previous PRs because the changes in the PR get lost, harder to review.

**Comment by ahgittin** [comment]
Actually the build failed when it got to the osgi init bundle (I spoke too soon, seeing core pass):

```
[INFO] Brooklyn OSGi init ................................ FAILURE [0.878s]
[INFO] Brooklyn Karaf .................................... SKIPPED
[INFO] Jetty config fragment ............................. SKIPPED
[INFO] Brooklyn Karaf Features ........................... SKIPPED
[INFO] Brooklyn Karaf Distro ............................. SKIPPED
[INFO] Brooklyn Karaf Shell Commands ..................... SKIPPED
[INFO] Brooklyn Karaf pax-exam itest ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:28.798s
[INFO] Finished at: Mon Mar 28 17:23:34 BST 2016
[INFO] Final Memory: 180M/580M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project brooklyn-karaf-init: Compilation failure: Compilation failure:
[ERROR] /private/tmp/brooklyn-server-71e8b35ca9680c4e1e443e883e4ba52c/karaf/init/src/main/java/org/apache/brooklyn/launcher/osgi/OsgiShutdownHandler.java:[21,37] cannot find symbol
[ERROR] symbol:   class ShutdownHandler
[ERROR] location: package org.apache.brooklyn.core.mgmt
[ERROR] /private/tmp/brooklyn-server-71e8b35ca9680c4e1e443e883e4ba52c/karaf/init/src/main/java/org/apache/brooklyn/launcher/osgi/OsgiShutdownHandler.java:[28,45] cannot find symbol
[ERROR] symbol: class ShutdownHandler
[ERROR] /private/tmp/brooklyn-server-71e8b35ca9680c4e1e443e883e4ba52c/karaf/init/src/main/java/org/apache/brooklyn/launcher/osgi/OsgiShutdownHandler.java:[31,5] method does not override or implement a method from a supertype
```

**Comment by neykov** [comment]
It was due to a missing commit 271d76ba08f411cb35ac85327a831c27b8276be6, had to force push to include it.

**Comment by ahgittin** [comment]
updated https://github.com/ahgittin/brooklyn-server/tree/all-osgi with everything including this and conflicts resolved.  building and testing it now.

**Pull request merged**
