### PR TITLE
Fix jmxmp connector in karaf

### PR DESCRIPTION
**Pull request by aledsage**
e.g. tomcat failed to reach service-up because it couldn't create the JMXMP connector due to classloading problems.

### CODE REVIEW

**Comment by justinThompson** [comment]
This also resolves the issues of policies not being registered into the catalog

**Comment by aledsage** [comment]
@justinThompson I extracted the catalog.bom policy issue into its own PR, and have merged it. Rebased this PR again against master.

The failing test here is possibly unrelated. I'll investigate further, but jenkins is also rebuilding:

```
2016-07-05 23:05:51,943 INFO  TESTNG FAILED: "Surefire test" - org.apache.brooklyn.camp.brooklyn.ConfigYamlTest.testDeferredSupplierToAttributeWhenReady() finished in 180 ms
java.lang.IllegalStateException
	at org.apache.brooklyn.util.guava.IllegalStateExceptionSupplier.get(IllegalStateExceptionSupplier.java:52)
	at org.apache.brooklyn.util.guava.IllegalStateExceptionSupplier.get(IllegalStateExceptionSupplier.java:26)
	at org.apache.brooklyn.util.guava.Maybe$Absent.getException(Maybe.java:276)
	at org.apache.brooklyn.util.guava.Maybe$Absent.get(Maybe.java:273)
	at org.apache.brooklyn.camp.brooklyn.ConfigYamlTest.testDeferredSupplierToAttributeWhenReady(ConfigYamlTest.java:207)
```

**Comment by aledsage** [comment]
Confirmed that test failure is unrelated. The problem is that when `entity.config().getNonBlocking()` is called with a deferred supplier value, it will kick off a task and then wait just a few millis for that taks to execute `deferredSupplier.get()`. If it times out, then it returns `Maybe.absent`. However, on apache jenkins the machine is often slow so the task doesn't complete in the given number of millis (even though `deferredSupplier.get()` doesn't need to block for anything).

**Comment by neykov** [comment]
LGTM, merging

**Pull request merged**
