### PR TITLE
Add more sensors for main.uri, based on the context, i.e public or not

### PR DESCRIPTION
**Pull request by tbouron**
Create 2 new sensors: `main.uri.mapped.public` and `main.uri.mapped.subnet`

### CODE REVIEW

**Comment by aledsage** [comment]
Build failed with:
```
GitHub pull request #378 to apache/brooklyn-server
[EnvInject] - Loading node environment variables.
Building remotely on ubuntu-eu2 (Ubuntu ubuntu ubuntu-eu docker) in workspace /home/jenkins/jenkins-slave/workspace/brooklyn-server-pull-requests
java.io.IOException: Failed to mkdirs: /home/jenkins/jenkins-slave/workspace/brooklyn-server-pull-requests
```

@tbouron can you kick this off again (e.g. by doing something like `git commit --amend && git push --force branch`)

**Comment by aledsage** [comment]
Changes look good, and low risk to me! Eye-baling the code, I don't see how they could cause any problems or build failures.

**Comment by tbouron** [comment]
@aledsage Force pushed, Jenkins is still complaining with the same error message. Something wrong on Apache Infra?

**Comment by aledsage** [comment]
I've checked this branch out locally, to check it. Merging now (as jenkins builds is not managing to even try to build this).

**Pull request merged**
