### PR TITLE
Fixing/disabling failing integration tests

### PR DESCRIPTION
**Pull request by neykov**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by neykov** [comment]
test this please

**Comment by neykov** [comment]
retest this please

**Comment by neykov** [comment]
run tests

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/brooklyn-server-pull-requests/2248/<h2>Build result: FAILURE</span></h2>[...truncated 5.88 MB...][INFO] ------------------------------------------------------------------------[INFO] Total time: 10:19 min[INFO] Finished at: 2017-06-02T15:56:29+00:00[INFO] Final Memory: 111M/821M[INFO] ------------------------------------------------------------------------Waiting for Jenkins to finish collecting data[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project brooklyn-camp: There are test failures.[ERROR] [ERROR] Please refer to /home/jenkins/jenkins-slave/workspace/brooklyn-server-pull-requests@2/camp/camp-brooklyn/target/surefire-reports for the individual test results.[ERROR] -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException[ERROR] [ERROR] After correcting the problems, you can resume the build with the command[ERROR]   mvn <goals> -rf :brooklyn-campchannel stoppedAdding one-line test results to commit status...Setting status of e3ec018c90172d1bb27596db9209aa15d6a31c46 to FAILURE with url https://builds.apache.org/job/brooklyn-server-pull-requests/2248/ and message: 'Build finished. 3890 tests run, 0 skipped, 1 failed.'Using context: Jenkins: brooklyn-server-pull-request
Failure

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/brooklyn-server-pull-requests/2249/
Success
--none--

**Comment by neykov** [comment]
run tests

**Comment by neykov** [comment]
run tests

**Comment by neykov** [comment]
retest this please

**Pull request merged**
