### PR TITLE
Serialize environment values - implement for all entities

### PR DESCRIPTION
**Pull request by neykov**
Builds on https://github.com/apache/brooklyn-server/pull/208

### CODE REVIEW

**Comment by grkvlt** [comment]
@neykov this is useful, although I don't much like the fact we have to do it explicitly everywhere. can't see a way of centralising it, unless we implement some kind of post-processor with a `Function<T,String> toString` as an option for every `ConfigKey` and a sensible default?

**Comment by grkvlt** [comment]
@neykov happy to merge as-is, anyway

**Comment by neykov** [comment]
That's very specific to bash environment serialization so doing a `toString` for config keys in general would need information on how the value would be used. I think it becomes too complex for little gain. In future I agree we could add object specific serialization when need arises.

**Comment by grkvlt** [comment]
@neykov OK, merging

**Pull request merged**
