### PR TITLE
modify jclouds logging categories to fix certain OOME's

### PR DESCRIPTION
**Pull request by ahgittin**

### CODE REVIEW

**Comment by andreaturli** [comment]
Lgtm although the extra comment for wire logger (suboptimal..) will be not needed as soon as I fix jclouds

**Comment by geomacy** [comment]
Do we need to add the same config in the karaf logging config - brooklyn-dist/karaf/apache-brooklyn/src/main/resources/etc/org.ops4j.pax.logging.cfg?

**Comment by ahgittin** [comment]
yes @geomacy - good spot, will add

**Comment by ahgittin** [comment]
@geomacy done in https://github.com/apache/brooklyn-dist/pull/55

**Pull request merged**
