### PR TITLE
Updated GCE features

### PR DESCRIPTION
**Pull request by drigodwin**
Added missing GCE dependency to features and moved to load order. Tested deployment on GCE (which was previously not working).

### CODE REVIEW

**Comment by andreaturli** [comment]
thanks @drigodwin, I wonder if we shouldn't use this https://github.com/jclouds/jclouds-karaf/blob/master/feature/src/main/feature/feature.xml and import, for example, https://github.com/jclouds/jclouds-karaf/blob/master/feature/src/main/feature/feature.xml#L32 to avoid this issues

**Comment by m4rkmckenna** [comment]
@andreaturli I agree ... has this been included in a JClouds release yet?

**Comment by andreaturli** [comment]
not yet

**Comment by drigodwin** [comment]
I agree @andreaturli, we should use this when it becomes available. I think we should also make this change in the meantime however as this fixes GCE in the short term.

**Comment by andreaturli** [comment]
lgtm

**Comment by andreaturli** [comment]
testing locally and merging shortly

**Comment by andreaturli** [comment]
thanks @drigodwin

**Pull request merged**
