### PR TITLE
Initial work to simplify the rest server

### PR DESCRIPTION
**Pull request by andreaturli**
- remove JsonNode from API interfaces
- refactor consistently toStringand hashCode and equals for the domain objects
- remove deprecated code
- simplified pom dependencies
- remove com.codehaus.jackson dependency and promote com.fasterxml.jackson usage
- adjust BrooklynJacksonSerializer to use jackson 2 api
- fix web.xml for rest-api and rest-client
- update feature.xml dependencies, following maven dependency changes

### CODE REVIEW

**Comment by andreaturli** [comment]
This PR is a porting of https://github.com/apache/incubator-brooklyn/pull/1177 to the new repo.

**Comment by neykov** [comment]
Looks great. Can you remove 'pom.xml.orig' and I'll merge it.

**Comment by andreaturli** [comment]
thanks @neykov for your review.
- removed `pom.xml.origin` - not sure why it was there, sorry :(
- rebased and squashed

let's wait for jenkins and eventually merge it

**Comment by neykov** [comment]
Failure is unrelated and builds fine on my machine. Merging.

**Pull request merged**
