### PR TITLE
Do not inherit entity config defaultDisplayName

### PR DESCRIPTION
**Pull request by bostko**
@aledsage could you review it.

### CODE REVIEW

**Comment by bostko** [comment]
Inherited configs are not persisted so the fix will work when applying to an Apache Brooklyn instance which already persisted such config values.

**Comment by bostko** [comment]
retest please

**Comment by bostko** [comment]
retest this please

**Comment by neykov** [comment]
LGTM

**Comment by iyovcheva** [comment]
Looks good

**Comment by aledsage** [comment]
LGTM; tests pass locally for me. Merging now.

---
Failure in jenkins looks unrelated (a timeout):

    Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: Invalid object ID 11 iota=46
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project brooklyn-launcher: There was a timeout or other error in the fork -> [Help 1]

**Pull request merged**
