### PR TITLE
Use dependencyManagement from Karaf as a bom

### PR DESCRIPTION
**Pull request by kemitix**
Apache Brooklyn uses a lot of the same dependencies are provided by Apache Karaf. However, we redeclare these dependencies and rely on notes and comments to upgrade them when Karaf is upgraded.

Karaf provides a `<dependencyManagement>` element that we can import into our parent `pom.xml`.

This PR does this and removes any duplicates. Where we use a conflicting/alternative version they have been grouped together and commented that they are overriding versions in Karaf. All of them are holding back to older versions of the dependency.

Some properties that are not used with a `<dependency>` are used within a `features.xml` file to declare a `<bundle dependency....>`. These have been grouped next to the `<karaf.version>` property to aid in remembering to update them when Karaf is upgraded.

The intention is to make future upgrades of Karaf easier by reducing the potential for conflicting versions. It also makes it clearer which dependencies are no longer matching those used by Karaf. Removing the relevant entry, and property (if not used in a `feature`) in our `pom.xml` would upgrade to the Karaf version.

`javax.xml.bind` and `javax.activation` libraries have been replaced with the Apache Servicemix versions that Karaf uses, to avoid the risk of classes being included from different sources.

Features that used `jetty` dependencies have been updated to use the Karaf-provided feature `jetty`. This removes the need to maintain a `<jetty.version>` property.

### CODE REVIEW

**Comment by kemitix** [comment]
There are problems being reported by `brooklyn-dist` when building againt this PR. Need to look into that before going ahead with this.

**Comment by aledsage** [comment]
I like the approach, the changes look good, but `brooklyn-dist` build fails for me with these changes due to the `maven-enforcer-plugin`:
```
[WARNING] 
Dependency convergence error for javax.xml.bind:jaxb-api:2.3.0 paths to dependency are:
+-org.apache.brooklyn:karaf-docker-image:1.0.0-SNAPSHOT
  +-org.apache.brooklyn:apache-brooklyn:1.0.0-SNAPSHOT
    +-org.apache.karaf.features:framework:4.2.2
      +-org.apache.karaf.features:base:4.2.2
        +-javax.xml.bind:jaxb-api:2.3.0
and
+-org.apache.brooklyn:karaf-docker-image:1.0.0-SNAPSHOT
  +-org.apache.brooklyn:apache-brooklyn:1.0.0-SNAPSHOT
    +-org.apache.karaf.features:framework:4.2.2
      +-org.apache.karaf.features:base:4.2.2
        +-org.glassfish.jaxb:jaxb-runtime:2.3.1
          +-javax.xml.bind:jaxb-api:2.3.1

[WARNING] Rule 2: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability the error(s) are [
Dependency convergence error for javax.xml.bind:jaxb-api:2.3.0 paths to dependency are:
+-org.apache.brooklyn:karaf-docker-image:1.0.0-SNAPSHOT
  +-org.apache.brooklyn:apache-brooklyn:1.0.0-SNAPSHOT
    +-org.apache.karaf.features:framework:4.2.2
      +-org.apache.karaf.features:base:4.2.2
        +-javax.xml.bind:jaxb-api:2.3.0
and
+-org.apache.brooklyn:karaf-docker-image:1.0.0-SNAPSHOT
  +-org.apache.brooklyn:apache-brooklyn:1.0.0-SNAPSHOT
    +-org.apache.karaf.features:framework:4.2.2
      +-org.apache.karaf.features:base:4.2.2
        +-org.glassfish.jaxb:jaxb-runtime:2.3.1
          +-javax.xml.bind:jaxb-api:2.3.1
]
```

Annoyingly, this seems to be a problem in Karaf 4.2.2 itself!

https://search.maven.org/artifact/org.apache.karaf.features/base/4.2.2/jar depends on:
```
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.0</version>
</dependency>
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>2.3.1</version>
</dependency>
```
And https://search.maven.org/artifact/org.glassfish.jaxb/jaxb-runtime/2.3.1/jar depends on v2.3.1 of `javax.xml.bind:jaxb-api`.

Therefore I'm not sure we can merge this! Maybe we could add some excludes or some temporary ugliness like that.

Note that karaf 4.2.3 is recently out as well, which I think will fix that incompatibility between jaxb-api version (to use v2.3.2 throughout). But not suggesting we rush to upgrade to that, and certainly not in this PR.

**Comment by kemitix** [comment]
@aledsage Updated: Overriding the dependency, much as karaf appear to do themselves, fixes this.

**Comment by jcabrerizo** [comment]
I can build Brooklyn and deploy some examples locally and on AWS. It looks great

**Comment by duncangrant** [comment]
Previously brooklyn was only doing the stop / restart thing twice during start.
Extra one seems to be related to jetty - but I'm not sure how to interpret the logs for this

**Comment by kemitix** [comment]
retest this please

job missing on jenkins

**Pull request merged**
