### PR TITLE
SshCommandEffector + shell.env

### PR DESCRIPTION
**Pull request by sjcorbett**
SshCommandEffector resolves shell.env against the target entity rather than always resolving it against the entity the effector is attached to. This also fixes the resolution of the execution directory.

### CODE REVIEW

**Comment by sjcorbett** [comment]
Resolution of shell environments is badly affected by the problem #385 fixes. For example when you invoke the effector created in this bluerint:

```yaml
location: localhost
services:
- type: brooklyn.entity.group.DynamicCluster
  id: cluster
  brooklyn.config:
    initialSize: 3
    memberSpec:
      $brooklyn:entitySpec:
        type: org.apache.brooklyn.entity.software.base.EmptySoftwareProcess
        brooklyn.config:
          shell.env:
            MEMBER_CFG: $brooklyn:config("cluster.member.id")
            MEMBER_ID: $brooklyn:attributeWhenReady("entity.id")

  - type: brooklyn.entity.software.ssh.SshCommandEffector
    brooklyn.config:
      name: test-effector
      shell.env:
        CLUSTER_ID: $brooklyn:attributeWhenReady("entity.id")
      command: 'echo "cluster=${CLUSTER_ID}, memberId=${MEMBER_ID}, member=${MEMBER_CFG}" >> /tmp/echo'
      executionTarget: members
```
You generally observe output like:
```
cluster=hgnwhpehtq, memberId=h0ea5qzz4k, member=1
cluster=hgnwhpehtq, memberId=hgnwhpehtq, member=
cluster=hgnwhpehtq, memberId=hgnwhpehtq, member=
```
In two of the three cases the entries in the member's `shell.env` were resolved against the cluster, not the member.

**Comment by geomacy** [comment]
👍 changes look good to me at a read through.

**Comment by aledsage** [comment]
LGTM; merging.

@sjcorbett I've also merged #385 - do we want to add any more tests (similar to your example yaml, that it gets the right entity id)?

**Comment by sjcorbett** [comment]
Thanks @geomacy and @aledsage. I'll write a test for the new behaviour. Is there any way to inject a mock SSH tool? Would be neat if the test could be a unit test rather than an integration test.

**Comment by aledsage** [comment]
@sjcorbett you can use `RecordingSshTool`. For example https://github.com/apache/brooklyn-server/blob/master/camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigParametersYamlTest.java#L452-L493 for how that can be used in a YAML blueprint.

**Pull request merged**
