### PR TITLE
BROOKLYN-358: karaf includes jclouds-api-swift

### PR DESCRIPTION
**Pull request by aledsage**

### CODE REVIEW

**Comment by geomacy** [comment]
👍 LGTM

**Comment by geomacy** [comment]
seems a bit strange we need both jars, I guess that's my ignorance of jclouds, but this change should do the job

**Comment by aledsage** [comment]
jenkins failure looks unrelated:
```
SUREFIRE-859: [GC 305415K->120999K(747520K), 0.2360390 secs]
SUREFIRE-859: [GC 305319K->121095K(747520K), 0.1644870 secs]
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project brooklyn-camp: There was a timeout or other error in the fork -> 
```
It looks to me like a memory leak issue, which is slowing down our JVM considerably.

I hope that https://github.com/apache/brooklyn-server/pull/375 will make things a lot better (and that https://github.com/apache/brooklyn-server/pull/368 has already made it considerably better).

---
The test that was executing and that seems to have been running for an extremely long time was:
```
2016-10-07 15:28:14,539 INFO  TESTNG INVOKING: "Surefire test" - org.apache.brooklyn.camp.brooklyn.DslAndRebindYamlTest.testDslAttributeWhenReadyRebindWhenResolved()
```

I think we need to also investigate that test, to see if it can ever hang.

**Comment by aledsage** [comment]
Thanks @geomacy. I'm not sure of the difference. When I tried using `openstack-swift` instead of `swift`, it failed with the error shown below.

```
2016-10-07 13:50:12,414 ERROR 121 o.a.b.l.c.BasicLauncher [FelixStartLevel] Subsystem for persistence had startup error (continuing with startup): org.apache.brooklyn.util.exceptions.FatalRuntimeException: Error initializing persistence subsystem: UncheckedExecutionException: org.jclouds.http.HttpResponseException: command: POST https://ams01.objectstorage.softlayer.net/auth/v1.0/tokens HTTP/1.1 failed with response: HTTP/1.1 400 Bad Request; content: [<html><h1>Bad Request</h1><p>The server could not comply with the request since it is either malformed or otherwise incorrect.</p><
/html>]
org.apache.brooklyn.util.exceptions.FatalRuntimeException: Error initializing persistence subsystem: UncheckedExecutionException: org.jclouds.http.HttpResponseException: command: POST https://ams0
1.objectstorage.softlayer.net/auth/v1.0/tokens HTTP/1.1 failed with response: HTTP/1.1 400 Bad Request; content: [<html><h1>Bad Request</h1><p>The server could not comply with the request since it is either malformed or otherwise incorrect.</p></html>]
```

**Comment by andreaturli** [comment]
`swift` is deprecated and will be replaced by `openstack-swift` from jclouds 2+

**Comment by aledsage** [comment]
Thanks @andreaturli - at some point we'll need to look into why `openstack-swift` failed with 1.9.2. I got the error below:
```
2016-10-07 13:50:12,414 ERROR 121 o.a.b.l.c.BasicLauncher [FelixStartLevel] Subsystem for persistence had startup error (continuing with startup): org.apache.brooklyn.util.exceptions.FatalRuntimeException: Error initializing persistence subsystem: UncheckedExecutionException: org.jclouds.http.HttpResponseException: command: POST https://ams01.objectstorage.softlayer.net/auth/v1.0/tokens HTTP/1.1 failed with response: HTTP/1.1 400 Bad Request; content: [<html><h1>Bad Request</h1><p>The server could not comply with the request since it is either malformed or otherwise incorrect.</p><
/html>]
org.apache.brooklyn.util.exceptions.FatalRuntimeException: Error initializing persistence subsystem: UncheckedExecutionException: org.jclouds.http.HttpResponseException: command: POST https://ams0
1.objectstorage.softlayer.net/auth/v1.0/tokens HTTP/1.1 failed with response: HTTP/1.1 400 Bad Request; content: [<html><h1>Bad Request</h1><p>The server could not comply with the request since it is either malformed or otherwise incorrect.</p></html>]
```

**Comment by andreaturli** [comment]
@aledsage yeah, I'm experiencing a weird behavior with openstack-swift against SL Object Store as well, hopefully I'll get to the bottom of it soon.

**Comment by andreaturli** [comment]
I suspect `openstack-swift` is designed with the assumption that the provider will offer at least keystone v2 api (which are already deprecated!) SL still uses v1 so POST /tokens is not available that's why the authN fails.

**Comment by aledsage** [comment]
@andreaturli well found - can you please raise an issue on https://issues.apache.org/jira/browse/BROOKLYN to capture that. And also an issue on https://issues.apache.org/jira/browse/JCLOUDS (assuming that this will require a fix in jclouds, to make it work with providers that still use keystone v1?).

**Comment by sjcorbett** [comment]
I've run into the issues discussed above. Was either issue filed? Is Brooklyn able to persist to SoftLayer's object store?

**Comment by neykov** [comment]
The fix to get SL working is to configure your object store location with:
```
jclouds.keystone.credential-type: tempAuthCredentials
```

**Pull request merged**
