### PR TITLE
JcloudsLocationCustomizer.onObtainError

### PR DESCRIPTION
**Pull request by neykov**
Makes customizers aware of obtain failures in case they need to clean up.
Also wraps the customizer calls into a delegate.

### CODE REVIEW

**Comment by neykov** [comment]
Updated the PR, good for review.

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by neykov** [comment]
ok to test

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/brooklyn-server-pull-requests/2247/
Success

**Comment by neykov** [comment]
Fixed the build errors.

**Comment by geomacy** [comment]
Build passes for me now, LGTM, merging.

**Pull request merged**
