### PR TITLE
Add contributing guidelines and PR template

### PR DESCRIPTION
**Pull request by tbouron**
Based on the recent discussion, I created a `CONTRIBUTING.md` (taken from [this page](https://brooklyn.apache.org/developers/how-to-contribute.html)) as well as a comprehensive GitHub PR template (new [GitHub feature](https://github.com/blog/2111-issue-and-pull-request-templates))

I plan to do the same in all Brooklyn's repos but want to make sure first that the common text is fine before opening the other PRs

### CODE REVIEW

**Comment by ahgittin** [comment]
Most PR's we get are good and the summaries provided are almost always clear and easy to read.  A template increases the burden on the people opening the PR which I see as counterproductive and makes them harder to read because it discourages the contributor from just cutting to the chase.  This particular template is onerous and patronising -- as though our goal is to put people off.

I don't see what purpose `CONTRIBUTING.md` achieves as that information is easy to find on our web site.  Have I missed us being inundated by people saying "Help I don't know how to contribute, if only you had another markdown file in the root" ?

The point in my ML post is that we need to be less prissy and more welcoming.  This PR takes us in the complete opposite direction.

**Comment by geomacy** [comment]
Have to say I certainly wouldn't be keen to fill out a template when creating a PR, even one much smaller than this.  Plus, thinking over what PRs on Brooklyn look like up to now, I don't people need a template - they're pretty well described, I think people are well enough aware of what info is needed when raising them.

**Comment by tbouron** [comment]
> This particular template is onerous and patronising

Patronising, seriously? I'm speechless here. FYI @ahgittin a `CONTRIBUTING.md` can be useful because [GitHub treats it a bit differently](https://github.com/blog/1184-contributing-guidelines)

Anyway, anybody else against this?

**Comment by drigodwin** [comment]
I think a `CONTRIBUTING.md` would be a good addition, it adds a link to the guidelines on the PR screen. Whilst you can look them up on the website as @ahgittin suggests, you have to know they exist. I can't see how it hurts to have it.

The PR template is slightly more contentious. I think we could have a more simplified example just indicating people should provide a good description of what the changes are. I find a vague title and `No description provided.` really annoying when going back over PRs for things like producing release notes.

**Comment by ahgittin** [comment]
@tbouron Yes, I find it patronising to give comments to tell people what to put in a title and a description, and to expect them to tick a box to say `[ ] I have read the [**CONTRIBUTING**](../CONTRIBUTING.md) document.`.

This PR neglects most of the process it advises (jira? motivation? testing? checklist?) -- suggesting it is just process for process's sake which I abhor.

I did wonder whether the `CONTRIBUTING.md` file got treated specially.  Even so it introduces more stuff the contributor has to look at, plus stuff for us to maintain, and files littering the root of a project -- meanwhile I'm not aware of actual problems we are encountering that this would solve.

The plain simple approach we currently have lets contributors focus on their content without distraction.

I'm strongly against any introduction of more process or bloat like this unless we have a clear problem that we expect it to solve.

@drigodwin Where there are aspects of a PR that are sub-optimal -- such as a vague title -- you are quite right to raise it.  But in the first instance it should be mentioned it in the PR where it arises.  if it's systemic send an email to the list to discuss, and on list we can decide whether the situation is such we need to become a kindergarten with rules posted blatantly in front of everyone who might be kind enough to contribute.

**Comment by tbouron** [comment]
Yeah, sure, whatever.

Was just trying to help but my take appears to be too "child-ish" so closing

**Pull request closed without merging**
