### PR TITLE
BasicSpecParameter: fix compatibility of persisted state

### PR DESCRIPTION
**Pull request by aledsage**
Support old-style persisted state, by implementing readResolve()

### CODE REVIEW

**Comment by aledsage** [comment]
@ahgittin @neykov could you take a look please?

**Comment by neykov** [comment]
How does `readResolve` work, is it called from somewhere?
Still think we need a way to bundle transformers with our code for cases like this.

**Comment by neykov** [comment]
Now is see it's used by `xstream`. That's a neat fix. Worth mentioning it in the comments, otherwise good to merge.

**Comment by aledsage** [comment]
Thanks @neykov - added comment saying "Automatically called by xstream (which is used under the covers by XmlMementoSerializer)."

Merging now.

**Pull request merged**
