### PR TITLE
Inclusion of catalog files inside other catalog files

### PR DESCRIPTION
**Pull request by neykov**
```
brooklyn.catalog:
  brooklyn.libraries: http://artifactory/my.jar
  items:
  - classpath://yaml-inside-my-jar.bom
  - id: sibling-item
    version: 0.1.0
    item:
      type: BasicEntity
```

### CODE REVIEW

**Comment by neykov** [comment]
Docs in https://github.com/apache/brooklyn-docs/pull/49

**Comment by neykov** [comment]
TODO: Support relative to the current context URLs.

**Comment by geomacy** [comment]
This all looks good to me.  I've cloned this PR and done various tests of my own, similar to the ones in the integration tests, and it all seems to work.  👍

**Comment by f377isB** [comment]
Looks good to me too - cloned, built and tested with consul blueprint (from Consul PR).

**Comment by ahgittin** [comment]
excellent.  merging.

re the ability to reference items relative to the BOM's location:  an easy way to do this is by uploading a ZIP containing all of it and we automatically make that a library.  harder will be to know the remote URL and try to resolve things relative to it.

i tend to think it's the former.  do you agree?

**Comment by neykov** [comment]
Thanks @ahgittin. Yes I meant the former in the TODO above.

**Comment by neykov** [comment]
Correction, I meant the latter - resolving URLs relative to the current source.

**Pull request merged**
