### PR TITLE
fix failing test searching for jsgui

### PR DESCRIPTION
**Pull request by ahgittin**
was assuming all dirs are checked out; now looks in classpath

### CODE REVIEW

**Comment by ahgittin** [comment]
optimism is so often misplaced.  we've fixed the rest launcher test problem; now we must tackle `org.apache.brooklyn.AssemblyTest.checkBrooklynCoreFeature` /cc @hzbarcea :

`org.ops4j.pax.swissbox.tracker.ServiceLookupException: gave up waiting for service org.apache.karaf.features.BootFinished`

**Comment by geomacy** [comment]
Always another hurdle... 😕

**Comment by hzbarcea** [comment]
I am getting a different error in server:
```
2016-02-08 00:07:21,325 INFO  BrooklynLeakListener.onFinish attempting to terminate all extant ManagementContexts: name=Surefire test; includedGroups=[]; excludedGroups=[Integration, Acceptance, Live, Broken, WIP]; suiteName=Surefire suite; outDir=/home/hadrian/dev/apache/repos/brooklyn-server/launcher/target/surefire-reports/Surefire suite: no org.apache.brooklyn.core.management.internal.LocalManagementContext available, so skipped
Tests run: 29, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 47.371 sec <<< FAILURE! - in TestSuite
testJavascriptWithoutRest(org.apache.brooklyn.rest.jsgui.BrooklynJavascriptGuiLauncherTest)  Time elapsed: 30.024 sec  <<< FAILURE!
```
Looking more into it in the morning.

**Comment by ahgittin** [comment]
@hzbarcea that's the error this PR fixes.  is that error running with this PR?

**Comment by ahgittin** [comment]
this improves things, so merging

**Pull request merged**
