### PR TITLE
Fix type-coercion to Iterable<?>

### PR DESCRIPTION
**Pull request by aledsage**

### CODE REVIEW

**Comment by ygy** [comment]
@aledsage LTGM. Tests are passing for me. Tested successfully with a BP which fails without it.

**Comment by geomacy** [comment]
LGTM.  @ygy what was your blueprint?

**Comment by ygy** [comment]
@geomacy You can find at https://gist.github.com/ygy/59c793028457c1f1f5a1f027df047fa6

**Comment by aledsage** [comment]
@m4rkmckenna it's an issue when we try to coerce from some complex yaml values to jclouds parameter values - e.g. we try to reflectively call `AzureTemplateOptions.secrets(Iterable<Secret>)` if you use something like:
```
location:
  azurecompute-arm:
    templateOptions:
      secrets:
      - sourceVault:
          id: myid
        vaultCertificates:
        - certificateUrl: myurl
          certificateStore: mystore
```

**Comment by geomacy** [comment]
Merging...

**Comment by geomacy** [comment]
Merging

**Pull request merged**
