### PR TITLE
Adds brooklyn-container-service code

### PR DESCRIPTION
**Pull request by grkvlt**
See [IP clearance details](http://incubator.apache.org/ip-clearance/brooklyn-container-service.html) for further details.

### CODE REVIEW

**Comment by neykov** [comment]
@grkvlt Instead of moving the resources in a separate commit shouldn't we do some history surgery, similar to the split-repo work, where the files will appear as always been at the current location?

**Comment by grkvlt** [comment]
@neykov I didn't move things like that, but remember there is no shared history for the commits, which is why things look like this. It's the best we can do...

**Comment by neykov** [comment]
Makes sense @grkvlt.

Tried to deploy to kubernetes, here are my findings so far:
  * classic Brooklyn - need to add the new jar as a dependency to the `brooklyn-all` module so it's included in the distribution
  * Karaf - need to add the new bundle plus its dependencies (kubernetes-client, openshift-client, okhttp,  etc) to `feature.xml`.

**Comment by drigodwin** [comment]
I've tested this connecting to a docker swarm, k8s and openshift endpoint. I was able to connect and deploy things on each so this all looks good to me. I'm going to merge now. Thankyou very much @grkvlt and all the other contributors.

**Pull request merged**
