### PR TITLE
Fail the build on purpose

### PR DESCRIPTION
**Pull request by neykov**

### CODE REVIEW

**Comment by neykov** [comment]
retest this please

**Comment by neykov** [comment]
retest this please

**Comment by neykov** [comment]
retest this please

**Comment by neykov** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/brooklyn-server-pull-requests/2300/
Build failure.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/brooklyn-server-pull-requests/2301/

**Comment by bostko** [comment]
@neykov how did you verify Jenkins merges the branch to master before building?

**Comment by neykov** [comment]
@bostko It doesn't, see https://issues.apache.org/jira/browse/INFRA-14302 for discussion.

**Pull request closed without merging**
