### PR TITLE
[SECURITY] Bump karaf.version from 4.2.2 to 4.2.3

### PR DESCRIPTION
**Pull request by kemitix**
Bumps `karaf.version` from 4.2.2 to 4.2.3.

Updates `karaf` from 4.2.2 to 4.2.3

Updates `org.apache.karaf.system.core` from 4.2.2 to 4.2.3

Updates `org.apache.karaf.shell.core` from 4.2.2 to 4.2.3

Signed-off-by: dependabot[bot] <support@dependabot.com>

### CODE REVIEW

**Comment by kemitix** [comment]
Sourced from The GitHub Security Advisory Database.

> Moderate severity vulnerability that affects org.apache.karaf:karaf and org.apache.karaf:apache-karaf
> Apache Karaf kar deployer reads .kar archives and extracts the paths from the "repository/" and "resources/" entries in the zip file. It then writes out the content of these paths to the Karaf repo and resources directories. However, it doesn't do any validation on the paths in the zip file. This means that a malicious user could craft a .kar file with ".." directory names and break out of the directories to write arbitrary content to the filesystem. This is the "Zip-slip" vulnerability - https://snyk.io/research/zip-slip-vulnerability. This vulnerability is low if the Karaf process user has limited permission on the filesystem. Any Apache Karaf releases prior 4.2.3 is impacted.

    Affected versions: ["< 4.2.3"]

**Comment by aledsage** [comment]
The change looks reasonable, but it’s still scary the knock-on consequences of a version bump like this (e.g. what else has bumped version).

If you've tested it @kemitix then I'm ok with us merging it. Can you confirm what testing you've done?

I need to write up some stuff (commands, debugging tips etc) from last time I fought with versions in karaf dependencies.

**Comment by kemitix** [comment]
@aledsage Needs a little more work. Testing had been pretty basic with just brooklyn-server. I'm seeing a maven enforcer error when I try to build the whole of brooklyn.

**Comment by nakomis** [comment]
@kemitix Can you take a look at this please to see if it is still relevant, and address the comments above if appropriate

Thanks

**Comment by kemitix** [comment]
Closed: Superceeded by #1068

**Pull request closed without merging**
