### PR TITLE
VanillaSoftwareProcess tests

### PR DESCRIPTION
**Pull request by aledsage**
For "	Don’t call postInstallCommand if skipInstall=true", why did we previous still call postInstall @grkvlt ?

The bulk of this PR is the unit testing of VanillaSoftwareProcess, using the `RecordSshTool` to stub out all the ssh commands.

Note the "Adds EffectorUtilsTest" is unrelated - I meant to include it in a PR a while ago, but accidentally missed it! We previously didn't have any tests that covered these methods directly.

### CODE REVIEW

**Comment by grkvlt** [comment]
@aledsage not sure about `postInstall()` but I wonder if there was an entity that relied on that behaviour in Clocker? I will check before we merge this...

**Comment by neykov** [comment]
It was something to do with entities setting object properties on `postInstall`, later required in the launch step. We got NPEs if `postInstall` isn't called.

**Comment by neykov** [comment]
LGTM

**Comment by aledsage-tmp** [comment]
@grkvlt any objections to me merging this? I'll do so later today, unless you say otherwise.

**Pull request merged**
