### PR TITLE
Adds constraint (required|forbidden)unlessAnyOf

### PR DESCRIPTION
**Pull request by aledsage**

### CODE REVIEW

**Comment by aledsage** [comment]
retest this please

Changed test config, to enable `Delete workspace before build starts`

**Comment by aledsage** [comment]
@kemitix I completely agree about the tests being cryptic. Passing four booleans in a row in a method signature is an anti-pattern: it is hard to read and very error-prone.

These tests were originally written by Alex - I did some minor improvements to their readability (see https://github.com/apache/brooklyn-server/commit/d19d2079b1a2b16c6de8c950b67a2daf0b8d3372). I decided it was hard to make it much more readable without significantly increasing the amount of code required.

On balance, because it is a test class and because the methods are private, it seemed ok to leave the methods as cryptic - unpleasant for code reviewers looking at a diff, but if you open up the class it's liveable with.

**Comment by geomacy** [comment]
Oh by the way I had to jump through a hoop or two to get Brooklyn built with this - I was initially getting build errors from `brooklyn-ui` with this in place; I had to rebase this PR against `master`, and even at that got a build error as follows when building from the `brooklyn` parent:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:07 min
[INFO] Finished at: 2018-10-21T22:09:15+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.1.6:verify (verify-brooklyn-ui-modularity-feature) on project brooklyn-ui-modularity-features: Verification failures: Verification failures:
[ERROR] 	Unable to resolve framework features
[ERROR] 	Unable to resolve framework features
[ERROR] 	Unable to resolve framework features
[ERROR] -> [Help 1]
```
oddly when I did
```
cd brooklyn-ui/modularity-server/features
mvn clean install -DskipTests
``` 
it worked, and then when I went back to the top and resumed the original build, that finally passed. What's that all about?

**Comment by geomacy** [comment]
Will merge this

**Pull request merged**
