### PR TITLE
[OSGI] brooklyn.properties & CAMP platform init

### PR DESCRIPTION
**Pull request by neykov**
Also share the code with classic launcher.

Getting an exception in the logs, which is coming from the `cxf-async-client` jar, used by winrm. Seems like a bundle init ordering issue. Can be ignored for the time being, the service being registered there is not used.
```
2016-03-09 18:41:49,298 | ERROR | ort.http.async]) | configadmin                      | 3 - org.apache.felix.configadmin - 1.8.8 | [org.osgi.service.cm.ManagedService, id=146, bundle=84/mvn:org.apache.cxf/cxf-rt-transports-http-hc/3.1.4]: Unexpected problem updating configuration org.apache.cxf.transport.http.async
java.lang.NullPointerException
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduitFactory.addListener(AsyncHTTPConduitFactory.java:285)[84:org.apache.cxf.cxf-rt-transports-http-hc:3.1.4]
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduitFactory.<init>(AsyncHTTPConduitFactory.java:144)[84:org.apache.cxf.cxf-rt-transports-http-hc:3.1.4]
	at org.apache.cxf.transport.http.asyncclient.Activator$ConduitConfigurer.updated(Activator.java:79)[84:org.apache.cxf.cxf-rt-transports-http-hc:3.1.4]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[3:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[3:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[3:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1444)[3:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1400)[3:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:143)[3:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:110)[3:org.apache.felix.configadmin:1.8.8]
	at java.lang.Thread.run(Thread.java:745)[:1.7.0_80]

```

### CODE REVIEW

**Comment by ahgittin** [comment]
nice

**Comment by ahgittin** [comment]
code changes look good and i've confirmed it builds and runs fine.  fewer items (apps, locations, etc) are still being pulled in by default when in osgi mode, but i think that's the `ServiceLoader` issue.

worth spending a few minutes to see if that error can be eliminated because it will frighten people but good to merge.  (i'll leave it to you in case the answer to the above question is different.)

**Comment by neykov** [comment]
Decided to stop troubleshooting before investing too much time - at the point where I figured out it's not really required for everything to work. But agree it needs to be addressed sooner or later.

Re missing items:
  * locations - due to service loader
  * catalog - there's something more going on there, will troubleshoot once this + the service loader fix lands. It's  a non-critical problem - brooklyn still can be used without it, so better address the immediate problems first.

**Comment by neykov** [comment]
NPE fixed in https://github.com/apache/cxf/pull/128 and https://github.com/apache/cxf/pull/129. Confirming it's harmless and can be ignored, but can't be suppressed from Brooklyn's side.

**Pull request closed without merging**
