### PR TITLE
Tidies - adjunct destroy, and better error messages

### PR DESCRIPTION
**Pull request by ahgittin**
Fixes a few minor things I've encountered:

* When invalid plans were sent, the error messages were awful.  Now they are more concise and sometimes more relevant.
* We never called `destroy` on adjuncts
* a couple other negligible things

### CODE REVIEW

**Comment by iuliana** [comment]
Unused imports in:
```
BrooklynComponentTemplateResolver,
BasicBrooklynTypeRegistry,
JcloudsWinrmingLiveTest,
PeriodicEffectorPolicyTest (log is declared and not used as well),
AdjunctResourceTest
```

3 test failures:
```
org.apache.brooklyn.camp.brooklyn.spi.dsl.TagsYamlTest.testBrooklynCampFailDslTags,
org.apache.brooklyn.camp.brooklyn.spi.dsl.TagsYamlTest.testBrooklynCampTagsFailNonList,
org.apache.brooklyn.camp.brooklyn.spi.dsl.DslYamlTest.testDslNonDeferredInvalidMethod
```

Also in the root `pom.xml` some dependencies were downgraded, maybe a reason for doing so should be provided. The test failures prevent the merging of the branch.

**Comment by ahgittin** [comment]
Unused imports and failed tests fixed.  Thanks.

I don't see any changes in `pom.xml`.  Maybe something was weird.  I've merged `master` so hopefully that will go away?

Does this look mergeable if the above succeed?  (We should see soon whether the build passes.)

**Comment by ahgittin** [comment]
the `AdjunctResource.testAddPolicy` isn't working.  pretty sure it was ... not sure what's going on.  will investigate.  marking this WIP until it's fixed.

**Comment by ahgittin** [comment]
should be fixed now @iuliana

**Comment by iuliana** [comment]
All issues have been resolved and the build now passes. This looks good to me.

**Pull request merged**
