### PR TITLE
Add logo urls to karaf catalog-classes.bom

### PR DESCRIPTION
**Pull request by aledsage**
Add `iconUrl: ...` for things in karaf's catalog-classes.bom

These use references to external URLs, rather than things on the classpath, because we don't want to rely on having started the catalog's bundles (or classloading from the "right" bundle) when returning icons.

### CODE REVIEW

**Comment by Graeme-Miller** [comment]
lgtm, but can you re-run the test, it failed with OutOfMemory exception

**Comment by neykov** [comment]
OOME fixed in https://github.com/apache/brooklyn-server/pull/250

**Comment by aledsage** [comment]
I rebased to include #250; jenkins is building again.

**Comment by aledsage** [comment]
Relies on https://github.com/apache/brooklyn-library/pull/50 for some of these icons.

Using `classpath://...` for the urls to get them from the local amp, rather than having to reach out to the public internet. We can do this, now that resource loading in karaf is working.

**Comment by aledsage** [comment]
apache/brooklyn-library#50 is now merged; merging this.

**Pull request merged**
