### PR TITLE
use http://httpbin instead of https for tests

### PR DESCRIPTION
**Pull request by andreaturli**
this should fix the build failures we are seeing after 16th March

cc @geomacy please have a look at this

### CODE REVIEW

**Comment by aledsage** [comment]
LGTM; waiting for jenkins to finish and then good to merge.

**Comment by andreaturli** [comment]
looks there is another problem with ssl in another test. Wonder if it's a jenkins issue?

**Comment by ahgittin** [comment]
Make sure unit tests run with no internet connectivity (no DNS lookup etc).  That might not be the Jenkins problem but it is a requirement of our unit tests.  If you need to do an http call, run a local mock server, or make it an integration test.

**Comment by andreaturli** [comment]
I agree `@Test(groups="Integration")` is better for this test.

Notice, though, the failing tests is different this time:

org.apache.brooklyn.camp.brooklyn.CompositeEffectorYamlRebindTest.testRebindWhenHealthy (from TestSuite)

**Comment by geomacy** [comment]
@andreaturli CompositeEffectorYamlRebindTest also uses httpbin.org, so it would need to be an integration test too.  The full list looks like 
- CompositeEffectorYamlRebindTest
- CompositeEffectorYamlTest
- HttpCommandEffectorYamlRebindTest
- HttpCommandEffectorYamlTest
and HttpCommandEffectorIntegrationTest which already has its tests as integration tests.

**Comment by geomacy** [comment]
Looks good to me but will need a couple more tests marked integration. I will merge this and do those tests.

**Pull request merged**
