### PR TITLE
Changed jackson version to 2.7.5

### PR DESCRIPTION
**Pull request by Graeme-Miller**

### CODE REVIEW

**Comment by sjcorbett** [comment]
Can you test that `brooklyn-tosca` works with this change please?

**Comment by neykov** [comment]
Since we are upgrading suggest doing this change as well https://github.com/neykov/brooklyn-server/commit/62613c05c2ba08c3ad9055d1fa3006f100a58b38.

I also tried bumping to latest releases available (with same major number) in https://github.com/neykov/brooklyn-server/commit/da1073484ec24b555fed0c0f40b89e561dc929a8 - seems to work fine deploying kubernetes.

**Comment by grkvlt** [comment]
@Graeme-Miller happy to merge once you cherry-pick https://github.com/neykov/brooklyn-server/commit/62613c05c2ba08c3ad9055d1fa3006f100a58b38 into this PR as well

**Comment by sjcorbett** [comment]
@grkvlt @Graeme-Miller I am not happy for this to be merged before you have confirmed or we have at least discussed what happens to the `brooklyn-tosca` dist.

**Comment by geomacy** [comment]
@sjcorbett, @Graeme-Miller, I will pull this and test it out with brooklyn-tosca when I've done my next commit.

**Comment by geomacy** [comment]
👍 LGTM; I have pulled this PR, built brooklyn with it and then brooklyn-tosca on top of that (actually using https://github.com/cloudsoft/brooklyn-tosca/pull/117) and I can deploy and undeploy a sample application successfully.

**Comment by sjcorbett** [comment]
@geomacy did you use the dist tgz that brooklyn-tosca builds? I will also test shortly.

**Comment by geomacy** [comment]
@sjcorbett good point, no, I was using the Karaf distro.

**Comment by ahgittin** [comment]
out of curiosity is there a reason for this bump?  if there is can you say what it is for posterity?  otoh if it's just good hygiene that's fine although probably we should do a sweep as i'm sure there are other stale versions.

**Comment by sjcorbett** [comment]
@ahgittin another downstream project has a dependency on https://github.com/fabric8io/kubernetes-client which requires the later version.

**Comment by neykov** [comment]
The version bump was held back on purpose due to incompatibility with brooklyn-tosca transitive dependencies. Now that we are running in Karaf we can finally update (to a semi-recent version).

Agree there are lots of stale library versions in there which need updating.

**Comment by sjcorbett** [comment]
I've tested Brooklyn 0.10.0-SNAPSHOT master + this PR against brooklyn-tosca master. The standard Tomcat/MySQL blueprint deployed fine from Alien4Cloud. The brooklyn-tosca dist includes these jars in its lib directory:
```
jackson-annotations-2.7.5.jar
jackson-core-2.7.5.jar
jackson-databind-2.7.5.jar
jackson-dataformat-xml-2.4.5.jar
jackson-dataformat-yaml-2.4.5.jar
jackson-datatype-joda-2.4.5.jar
jackson-jaxrs-base-2.7.5.jar
jackson-jaxrs-json-provider-2.7.5.jar
jackson-module-jaxb-annotations-2.7.5.jar
```
By the look of it the 2.4.5 dependencies have come from `io.swagger:swagger-core` and `swagger-jaxrs` via `brooklyn-utils-rest-swagger`. 

So sounds like we're good to go but keeping this at the back of our minds. @ahgittin do you think we need to maintain `brooklyn-tosca-dist` any more?

**Comment by ahgittin** [comment]
Worth testing that the apidocs (Swagger REST docs) page works with these versions?

+1 to dropping `brooklyn-tosca-dist` in favour of the karaf way.  `brooklyn-tosca` docs and `README` probably will need updating also.

**Comment by Graeme-Miller** [comment]
I have just tested the swagger page works as expected with this PR.

**Comment by neykov** [comment]
That's a good spot @sjcorbett. The jackson library version mix seems important. I think it's better to stick to the same version (even if higher than required for swagger), than to risk incompatibility. It's higher risk to use two parts of the library with different versions than upgrade all of them.

Another reason to upgrade everything is that in Karaf we are explicitly adding the dependencies and pinning them to  the `fasterxml.jackson.version`. This causes the classic distribution to have a different mix of jars than the karaf one - best to keep them consistent.

**Comment by Graeme-Miller** [comment]
replacing with:
https://github.com/apache/brooklyn-client/pull/28
https://github.com/apache/brooklyn-server/pull/339

**Pull request closed without merging**
