### PR TITLE
deserializingClassRenames: handle renames in ConfigInheritance

### PR DESCRIPTION
**Pull request by aledsage**

### CODE REVIEW

**Comment by bostko** [comment]
Looks good!

**Comment by aledsage** [comment]
jenkins test failure is unrelated:
```
org.apache.brooklyn.feed.jmx.RebindJmxFeedTest.testJmxFeedIsPersisted

2016-10-10 14:00:19,963 INFO  TESTNG FAILED: "Surefire test" - org.apache.brooklyn.feed.jmx.RebindJmxFeedTest.testJmxFeedIsPersisted() finished in 185373 ms
java.rmi.server.ExportException: Port already in use: 40123; nested exception is: 
	java.net.BindException: Address already in use
	at sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:340)
	at sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:248)
	at sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:411)
	at sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
	at sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:207)
	at sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:122)
	at sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:108)
	at java.rmi.registry.LocateRegistry.createRegistry(LocateRegistry.java:203)
	at mx4j.tools.naming.NamingService.start(NamingService.java:67)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:292)
	at com.sun.proxy.$Proxy520.start(Unknown Source)
	at org.apache.brooklyn.entity.software.base.test.jmx.JmxService.<init>(JmxService.java:103)
	at org.apache.brooklyn.entity.software.base.test.jmx.JmxService.<init>(JmxService.java:80)
	at org.apache.brooklyn.feed.jmx.RebindJmxFeedTest.runJmxFeedIsPersisted(RebindJmxFeedTest.java:99)
	at org.apache.brooklyn.feed.jmx.RebindJmxFeedTest.testJmxFeedIsPersisted(RebindJmxFeedTest.java:86)
Caused by: java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:376)
	at java.net.ServerSocket.bind(ServerSocket.java:376)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at java.net.ServerSocket.<init>(ServerSocket.java:128)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createServerSocket(RMIDirectSocketFactory.java:45)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createServerSocket(RMIMasterSocketFactory.java:344)
	at sun.rmi.transport.tcp.TCPEndpoint.newServerSocket(TCPEndpoint.java:666)
	at sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:329)
	... 57 more
```

Unfortunately @ahgittin (cc @neykov) that means your 3-minute loop in `JmxService` constructor (to retry the `namingServiceMBean.start()`) didn't fix the problem.

**Comment by aledsage** [comment]
Merging now as the build got far enough to confirm the new test passes, and thus the fix works.

**Comment by bostko** [comment]
@aledsage how Jenkins machine is running tests? Does it execute tests concurrently with other PRs?

**Comment by aledsage** [comment]
@bostko yes, PRs are run in parallel so something else might be consuming the port. I'd have thought this 3 minute retry would have been enough to get around that. 

It's possible this port number is being consumed by a completely different service for many minutes, but that seems less likely.

**Pull request merged**
