### PR TITLE
Remove jersey compatibility

### PR DESCRIPTION
**Pull request by neykov**
My favourite kind of PRs -  0 additions and 9,808 deletions.

Now that 0.9.0 is branched we can remove the jersey compatibility.

### CODE REVIEW

**Comment by neykov** [comment]
Build failures fixed in #94. Once merged I expect some conflicts here, so will fix and trigger a rebuild.

**Comment by ahgittin** [comment]
delicious!  however is the passwordless login mentioned in #92 fixed?  not strictly a pre-req for this as we've already switched to cxf as the default but it is a high priority.

**Comment by neykov** [comment]
yes, completely fixed in #94

**Comment by sjcorbett** [comment]
@ahgittin @neykov Are you ready for this to be merged?

**Comment by neykov** [comment]
Good to go. Thanks!

**Pull request merged**
