### PR TITLE
Bumps karaf version to 4.2.7 (latest)

### PR DESCRIPTION
**Pull request by nakomis**

### CODE REVIEW

**Comment by jbonofre** [comment]
LGTM, I will merge when Jenkins is happy.

**Comment by ahgittin** [comment]
Note:  we needed to

`rm -rf ./org/ops4j/pax/logging/1.11.2/`

to get this to work.  Seems an old version of the POM (at this non-SNAPSHOT version!!!) did not call out the knopflerfish repository.  (And the official knopflerfish repository does not work.)

**Comment by ahgittin** [comment]
You may also need:

```
 <repository>
      <id>Knopflerfish 6 Repository</id>
      <name>Knopflerfish 6 Releases Repository</name>
      <url>http://resources.knopflerfish.org/repo/maven2/release/</url> 
</repository>
```

in your `settings.xml` ... @jbonofre is this known?

**Comment by ahgittin** [comment]
Also note https://github.com/apache/brooklyn-server/pull/1067#issuecomment-562530931

**Pull request merged**
