### PR TITLE
Enable more tests fixed by sensor order guarantees

### PR DESCRIPTION
**Pull request by ahgittin**
As @neykov mentions on #860 we've fixed tests attempted to be fixed in #641 described in https://issues.apache.org/jira/browse/BROOKLYN-525 .

This is the test-only subset of that closed PR.  Curious to see how it fares in jenkins.  Worth retesting this a couple times to make sure the items are fixed.

### CODE REVIEW

**Comment by ahgittin** [comment]
retest this please

first one aborted for no clear reason (tests included here passed):  https://builds.apache.org/job/brooklyn-server-pull-requests/2685/

```
2017-10-19 17:43:49,521 INFO  TESTNG PASSED CONFIGURATION: "Surefire test" - @BeforeMethod org.apache.brooklyn.test.framework.LoopOverGroupMembersTestCaseTest.setup() finished in 29 ms
2017-10-19 17:43:49,521 INFO  TESTNG INVOKING: "Surefire test" - org.apache.brooklyn.test.framework.LoopOverGroupMembersTestCaseTest.testNotTargetingGroup()
channel stopped
Adding one-line test results to commit status...
Setting status of bc0b392654624b3e36c411d1e555858a2e1cf1ff to FAILURE with url https://builds.apache.org/job/brooklyn-server-pull-requests/2685/ and message: 'FAILURE
 4586 tests run, 0 skipped, 0 failed.'
Using context: Jenkins: brooklyn-server-pull-request
Finished: ABORTED
```

**Comment by aledsage** [comment]
retest this please

**Comment by aledsage** [comment]
retest this please

**Comment by aledsage** [comment]
retest this please

Test passed first time, and then failed with an unrelated test-failure the second time (captured below). Kicking it off a third time.

```
java.lang.AssertionError: failed succeeds-eventually, 21 attempts, 3000ms elapsed: AssertionError: entity=Application[kgg9to9f]; attribute=Sensor: service.state (org.apache.brooklyn.core.entity.lifecycle.Lifecycle) expected [stopped] but found [stopping]
	at org.apache.brooklyn.core.entity.lifecycle.ServiceStateLogicTest.assertAttributeEqualsEventually(ServiceStateLogicTest.java:339)
	at org.apache.brooklyn.core.entity.lifecycle.ServiceStateLogicTest.testStopsNicelyToo(ServiceStateLogicTest.java:143)
Caused by: java.lang.AssertionError: entity=Application[kgg9to9f]; attribute=Sensor: service.state (org.apache.brooklyn.core.entity.lifecycle.Lifecycle) expected [stopped] but found [stopping]
	at org.apache.brooklyn.core.entity.lifecycle.ServiceStateLogicTest.assertAttributeEqualsEventually(ServiceStateLogicTest.java:339)
	at org.apache.brooklyn.core.entity.lifecycle.ServiceStateLogicTest.testStopsNicelyToo(ServiceStateLogicTest.java:143)
```

**Comment by ahgittin** [comment]
need to fix `org.apache.brooklyn.core.entity.lifecycle.ServiceStateLogicTest` - this is happening a fair bit now on jenkins (never locally).  also `org.apache.brooklyn.enricher.stock.UpdatingMapTest.testUpdateMapEmitsEventOnChange`.

(adding the words "non-deterministic test failures" so we can search for them again)

passed here though so good to merge

**Pull request merged**
